(() => {
  "use strict";
  const game = window.KI_GAME_DATA || {meta:{},species:{}};
  const C = window.KI_GUIDE_CONTENT;
  if (!C) return;
  const root = document.getElementById("guideRoot");
  const page = document.body.dataset.page || "guide";
  const state = {lang:localStorage.getItem("ki-rules-lang")||"th",query:"",diet:"all",mutationCategory:"all"};
  if(!["th","en","vi"].includes(state.lang)) state.lang="th";
  const tx=v=>v==null?"":(typeof v==="string"||typeof v==="number"?String(v):(v[state.lang]??v.en??v.th??v.vi??""));
  const U=()=>C.ui[state.lang]||C.ui.en;
  const aliasFor=name=>tx(C.speciesAliases?.[name]||name);
  const speciesLabel=name=>state.lang==="en"?name:(aliasFor(name)===name?name:aliasFor(name)+" — "+name);
  const dietLabel=v=>{const m={Carnivore:{th:"กินเนื้อ (Carnivore)",en:"Carnivore",vi:"Ăn thịt (Carnivore)"},Herbivore:{th:"กินพืช (Herbivore)",en:"Herbivore",vi:"Ăn cỏ (Herbivore)"},Omnivore:{th:"กินได้ทั้งพืชและเนื้อ (Omnivore)",en:"Omnivore",vi:"Ăn tạp (Omnivore)"}};return tx(m[v]||v)};
  const categoryLabel=v=>({Lifecycle:U().catLifecycle,"Slot Exclusive":U().catSlot,Unlockable:U().catUnlockable,"Test / Horde":U().catTest,Removed:U().catRemoved}[v]||v);
  const conditionLabel=v=>v==="active"?U().activeCondition:v==="passive"?U().passiveCondition:v;
  const restrictionLabel=v=>String(v||"").replace(/Female Only/g,state.lang==="th"?"เฉพาะตัวเมีย":state.lang==="vi"?"Chỉ con cái":"Female Only").replace(/Group Leader Only/g,state.lang==="th"?"เฉพาะหัวหน้ากลุ่ม":state.lang==="vi"?"Chỉ trưởng nhóm":"Group Leader Only").replace(/Carnivore/g,state.lang==="th"?"กินเนื้อ":state.lang==="vi"?"Ăn thịt":"Carnivore").replace(/Herbivore/g,state.lang==="th"?"กินพืช":state.lang==="vi"?"Ăn cỏ":"Herbivore").replace(/Omnivore/g,state.lang==="th"?"กินได้ทั้งสองแบบ":state.lang==="vi"?"Ăn tạp":"Omnivore");
  const E=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const F=(v,d=1)=>v==null||!Number.isFinite(Number(v))?"N/A":new Intl.NumberFormat("en-US",{maximumFractionDigits:d}).format(Number(v));
  const KG=v=>v==null?"N/A":F(v,1)+" kg";
  const KMH=v=>v==null?"N/A":F(v*.036,1)+" km/h";
  const PCT=v=>v==null?"N/A":((v>=0?"+":"")+F(v,1)+"%");
  function wb(p){return p&&(p.w===1||p.w===3)} function wa(p){return p&&(p.w===2||p.w===3)}
  function bz(a,b,c,d,t){const q=1-t;return q*q*q*a+3*q*q*t*b+3*q*t*t*c+t*t*t*d}
  function rw(a,b,t){const span=b.t-a.t,target=(t-a.t)/span,leave=a.lt??0,arrive=b.at??0;let ang=Math.atan(leave);const lw=wa(a)?(a.lw??0):Math.hypot(span,leave*span)/3;const p1t=Math.cos(ang)*lw+a.t,p1v=Math.sin(ang)*lw+a.v;ang=Math.atan(arrive);const aw=wb(b)?(b.aw??0):Math.hypot(span,arrive*span)/3;const p2t=-Math.cos(ang)*aw+b.t,p2v=-Math.sin(ang)*aw+b.v,c1=(p1t-a.t)/span,c2=(p2t-a.t)/span;let lo=0,hi=1;for(let i=0;i<50;i++){const m=(lo+hi)/2;bz(0,c1,c2,1,m)<target?lo=m:hi=m}return bz(a.v,p1v,p2v,b.v,(lo+hi)/2)}
  function rc(points,t){if(!Array.isArray(points)||!points.length)return null;const first=points[0],last=points[points.length-1];if(t<=first.t)return first.v;if(t>=last.t)return last.v;for(let i=0;i<points.length-1;i++){const a=points[i],b=points[i+1];if(t<a.t||t>b.t)continue;const span=b.t-a.t;if(span<=0)return a.v;const p=(t-a.t)/span;if(!a.c)return a.v+(b.v-a.v)*p;if(a.w||b.w)return rw(a,b,t);const m0=(a.lt??0)*span,m1=(b.at??0)*span,p2=p*p,p3=p2*p;return(2*p3-3*p2+1)*a.v+(p3-2*p2+p)*m0+(-2*p3+3*p2)*b.v+(p3-p2)*m1}return null}
  function cv(s,k,t,path){const c=s&&s.curves&&s.curves[k];return c?rc(path==="prime"?c.prime:c.frail,t):null}
  function ms(s,t,path){const attack=cv(s,"AttackPower",t,path);return{weight:cv(s,"Weight",t,path),speed:cv(s,"SprintSpeed",t,path),attack:attack,bite:attack!=null&&s.damageBite!=null?attack*s.damageBite:null}}
  function df(v,b){return v==null||b==null||b===0?null:(v-b)/Math.abs(b)*100}
  function hero(title,lead,extra){return '<section class="hero"><span class="eyebrow">KINGDOMS ISLE · EVRIMA FIELD CODEX</span><h1>'+title+'</h1><p>'+lead+'</p>'+(extra||"")+'</section>'}
  function source(){return ""}
  function header(){document.documentElement.lang=state.lang;document.querySelectorAll(".lang-btn").forEach(b=>b.classList.toggle("active",b.dataset.lang===state.lang));document.querySelectorAll("[data-ui]").forEach(el=>{const k=el.dataset.ui;if(U()[k])el.textContent=U()[k]})}
  function hub(){root.innerHTML=hero('GAME <span>GUIDE</span>',E(tx(U().guideLead)),'<div class="notice"><strong>SERVER RULES ≠ GAME GUIDE</strong><br>'+E(tx(U().guideNotice))+'</div>')+'<section class="section"><div class="section-head"><div><span class="eyebrow">'+E(U().fieldDirectory)+'</span><h2>'+E(U().home)+'</h2></div></div><div class="card-grid"><a class="hub-card" href="/viewer/?species=Tyrannosaurus&growth=75&path=frail"><div class="icon">◈</div><small>'+E(U().evrimaReference)+'</small><h3>'+E(state.lang==="th"?"3D DINOSAUR VIEWER":state.lang==="vi"?"TRÌNH XEM KHỦNG LONG 3D":"3D DINOSAUR VIEWER")+'</h3><p>'+E(state.lang==="th"?"ดู Tyrannosaurus แบบ 3D ปรับ Growth, Prime/Frail และ Animation ได้แบบเรียลไทม์":state.lang==="vi"?"Xem Tyrannosaurus 3D với Growth, Prime/Frail và Animation theo thời gian thực.":"Explore Tyrannosaurus in 3D with real-time Growth, Prime/Frail and Animation controls.")+'</p></a>'+C.hub.map(c=>'<a class="hub-card" href="'+c.href+'"><div class="icon">'+c.icon+'</div><small>'+E(U().evrimaReference)+'</small><h3>'+E(U()[c.key])+'</h3><p>'+E(tx(c.desc))+'</p></a>').join("")+'</div></section>'+source(C.sources.species,"Core species data")}
  function speciesList(){return Object.entries(game.species||{}).filter(x=>x[1]&&x[1].released===true).map(x=>Object.assign({name:x[0]},x[1]))}
  function speciesCard(s){const a=ms(s,.75,"frail");return '<article class="species-card" data-species="'+E(s.name)+'" tabindex="0" role="link"><div class="badges"><span class="badge current">'+E(U().current)+'</span><span class="badge">'+E(dietLabel(s.diet?.type||"N/A"))+'</span></div><h3>'+E(speciesLabel(s.name))+'</h3><p>'+E(U().dataset)+' '+E(game.meta.dataset||"")+'</p><div class="stats"><div class="mini-stat"><small>'+E(U().weight)+'</small><strong>'+KG(a.weight)+'</strong></div><div class="mini-stat"><small>'+E(U().speed)+'</small><strong>'+KMH(a.speed)+'</strong></div><div class="mini-stat"><small>'+E(U().bite)+'</small><strong>'+F(a.bite,1)+'</strong></div><div class="mini-stat"><small>'+E(U().dietType)+'</small><strong>'+E(dietLabel(s.diet?.type||"N/A"))+'</strong></div></div></article>'}
  function dinosaurs(){const q=new URLSearchParams(location.search),sel=q.get("species");if(sel&&game.species[sel]?.released===true){speciesDetail(sel,game.species[sel]);return}const allSpecies=speciesList(),diets=[...new Set(allSpecies.map(s=>s.diet?.type).filter(Boolean))].sort();const needle=state.query.trim().toLowerCase();const list=allSpecies.filter(s=>{const aliases=C.speciesAliases?.[s.name];const hay=[s.name,aliases?.th,aliases?.en,aliases?.vi,s.diet?.type,dietLabel(s.diet?.type)].filter(Boolean).join(" ").toLowerCase();return(!needle||hay.includes(needle))&&(state.diet==="all"||s.diet?.type===state.diet)});root.innerHTML=hero('<span>DINOSAUR</span> DATABASE',E(tx({th:"รวม Species ที่เปิดให้เล่นใน EVRIMA ปัจจุบันเท่านั้น โดยไม่รวม Legacy หรือ unreleased",en:"Current released EVRIMA species only — Legacy and unreleased content is excluded.",vi:"Chỉ gồm Species EVRIMA đang phát hành, không trộn Legacy hoặc unreleased."})),'<div class="hero-meta"><span class="meta-chip"><strong>'+allSpecies.length+'</strong> '+E(U().releasedSpecies)+'</span><span class="meta-chip">'+E(U().dataset)+' <strong>'+E(game.meta.dataset||"N/A")+'</strong></span></div>')+'<section class="section"><div class="toolbar species-toolbar"><div class="field species-search-field"><label>'+E(U().search)+'</label><input id="speciesSearch" type="search" autocomplete="off" value="'+E(state.query)+'" placeholder="'+E(U().speciesSearch)+'"><small class="field-help">'+E(U().searchHint)+'</small></div><div class="field"><label>Species</label><select id="speciesSelect"><option value="">'+E(U().chooseSpecies)+'</option>'+allSpecies.map(s=>'<option value="'+E(s.name)+'">'+E(speciesLabel(s.name))+'</option>').join("")+'</select><small class="field-help">'+E(U().selectHelp)+'</small></div><div class="field"><label>'+E(U().dietType)+'</label><select id="dietFilter"><option value="all">'+E(U().all)+'</option>'+diets.map(d=>'<option '+(state.diet===d?"selected":"")+' value="'+E(d)+'">'+E(dietLabel(d))+'</option>').join("")+'</select></div><div class="field"><label>'+E(U().status)+'</label><select disabled><option>'+E(U().current)+'</option></select></div></div><div class="species-grid">'+(list.length?list.map(speciesCard).join(""):'<div class="empty">'+E(U().noResults)+'</div>')+'</div></section>';document.getElementById("speciesSearch")?.addEventListener("input",e=>{state.query=e.target.value;dinosaurs()});document.getElementById("speciesSelect")?.addEventListener("change",e=>{if(e.target.value)location.href="/dinosaurs/?species="+encodeURIComponent(e.target.value)});document.getElementById("dietFilter")?.addEventListener("change",e=>{state.diet=e.target.value;dinosaurs()});bindSpecies()}
  function speciesDetail(name,s){
    const defs=[["adult75",.75,"frail"],["frail875",.875,"frail"],["prime875",.875,"prime"],["frail100",1,"frail"],["prime100",1,"prime"]];
    const rows=defs.map(r=>({key:r[0],val:ms(s,r[1],r[2])})),base=rows[0].val,foods=s.diet?.menu||s.diet?.sources||{},attacks=Object.keys(s.damage||{});
    const list=(title,arr)=>'<div class="diet-box"><b>'+title+'</b>'+((arr||[]).length?(arr||[]).map(x=>'<span>'+E(x)+'</span>').join(""):'<span>N/A</span>')+'</div>';
    const mobile=rows.map(r=>'<div class="mobile-stat"><h4>'+E(U()[r.key])+'</h4><dl><dt>'+E(U().weight)+'</dt><dd>'+KG(r.val.weight)+'</dd><dt>'+E(U().speed)+'</dt><dd>'+KMH(r.val.speed)+'</dd><dt>'+E(U().bite)+'</dt><dd>'+F(r.val.bite,1)+'</dd><dt>'+E(U().difference)+'</dt><dd>'+(r.key==="adult75"?"-":PCT(df(r.val.weight,base.weight))+" / "+PCT(df(r.val.speed,base.speed))+" / "+PCT(df(r.val.bite,base.bite)))+'</dd></dl></div>').join("");
    const B=C.buildUi?.[state.lang]||C.buildUi?.en||{};
    const mutByName=Object.fromEntries((C.mutations||[]).map(m=>[m.name,m]));
    const assignSlots=(items)=>{
      const valid=items.every(m=>m&&m.status==="current"&&Array.isArray(m.equipSlots)&&m.equipSlots.length);
      if(!valid)return null;
      const ordered=items.map((m,i)=>({m,i,slots:[...m.equipSlots]})).sort((a,b)=>a.slots.length-b.slots.length||a.i-b.i);
      const used=new Set(),assignment={};
      const walk=(idx)=>{
        if(idx>=ordered.length)return true;
        const it=ordered[idx];
        for(const slot of it.slots){
          if(slot<1||slot>4||used.has(slot))continue;
          used.add(slot);assignment[it.i]=slot;
          if(walk(idx+1))return true;
          used.delete(slot);delete assignment[it.i];
        }
        return false;
      };
      return walk(0)?assignment:null;
    };
    const buildCards=(C.speciesBuilds?.[name]||[]).map((build,buildIndex)=>{
      const role=C.roleProfiles?.[build.role];
      const items=(build.mutations||[]).map(n=>mutByName[n]).filter(Boolean);
      const assignment=assignSlots(items);
      if(!role||items.length!==build.mutations.length||!assignment)return "";
      const ordered=items.map((m,i)=>({m,slot:assignment[i]})).sort((a,b)=>a.slot-b.slot);
      return '<article class="build-card"><div class="build-card-head"><div><span class="build-kicker">'+E(B.community||"COMMUNITY RECOMMENDATION")+'</span><h3>'+E(tx(role.name))+'</h3><p>'+E(tx(role.desc))+'</p></div><span class="build-index">'+String(buildIndex+1).padStart(2,"0")+'</span></div><div class="build-mutations">'+ordered.map(({m,slot})=>'<div class="build-mutation"><div class="build-mutation-top"><strong>'+E(m.name)+'</strong><span class="slot-pill">SLOT '+slot+(slot===4?' · PRIME ELDER':'')+'</span></div><div class="build-reason"><span>'+E(B.why||"Why")+'</span><p>'+E(tx(m.effect))+(m.value?' · '+E(m.value):'')+'</p></div></div>').join("")+'</div><div class="build-foot"><div><span>'+E(B.strength||"Strength")+'</span><p>'+E(tx(role.strength))+'</p></div><div><span>'+E(B.tradeoff||"Trade-off")+'</span><p>'+E(tx(role.tradeoff))+'</p></div></div></article>';
    }).filter(Boolean).join("");
    const buildsSection=buildCards?'<section class="section species-builds-section"><div class="section-head"><div><span class="eyebrow">COMMUNITY RECOMMENDATION</span><h2>'+E(B.title||"RECOMMENDED BUILDS")+'</h2><p>'+E(B.lead||"")+'</p></div></div><div class="build-grid">'+buildCards+'</div></section>':'';
    root.innerHTML='<div class="breadcrumbs"><a href="/dinosaurs/">← '+E(U().dinosaurs)+'</a><span>/</span><b>'+E(name)+'</b><a class="nav-pill" href="/viewer/?species='+encodeURIComponent(name)+'&growth=75&path=frail">3D VIEWER</a></div>'+hero(E(name),E(tx({th:"ข้อมูล Current EVRIMA พร้อมค่าจาก game-data และแนวทาง Mutation แยกตาม Species",en:"Current EVRIMA game-data snapshot with Species-specific Mutation guidance.",vi:"Dữ liệu EVRIMA hiện tại cùng gợi ý Mutation riêng cho từng Species."})),'<div class="hero-meta"><span class="meta-chip">'+E(dietLabel(s.diet?.type||"N/A"))+'</span><span class="meta-chip"><strong>'+E(U().current)+'</strong></span><span class="meta-chip">'+E(game.meta.dataset||"")+'</span></div>')+
    '<section class="section detail-shell species-detail-section"><article class="detail-card"><span class="eyebrow">'+E(U().speciesData)+'</span><h2>'+E(name)+'</h2><div class="stats" style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:16px"><div class="mini-stat"><small>'+E(U().weight)+'</small><strong>'+KG(base.weight)+'</strong></div><div class="mini-stat"><small>'+E(U().speed)+'</small><strong>'+KMH(base.speed)+'</strong></div><div class="mini-stat"><small>'+E(U().bite)+'</small><strong>'+F(base.bite,1)+'</strong></div></div><h3 style="margin-top:22px">'+E(U().preferredFood)+'</h3><div class="diet-lists">'+list("α / CARB",foods.carb)+list("γ / LIPID",foods.lipid)+list("β / PROTEIN",foods.protein)+'</div></article><article class="detail-card"><span class="eyebrow">'+E(U().attacks)+'</span><h3>'+E(U().attacks)+'</h3><div class="attack-list">'+(attacks.length?attacks.map(a=>'<span class="attack-chip">'+E(a)+(s.damage?.[a]!=null?" · base "+F(s.damage[a],2):"")+'</span>').join(""):'<span class="na">N/A</span>')+'</div><div class="notice"><strong>'+E(U().derived)+'</strong><br>'+E(tx({th:"Bite / Attack = AttackPower curve × base attack value; ค่าที่ไม่มี source ยืนยันจะแสดง N/A",en:"Bite / Attack = AttackPower curve × base attack value; missing source values remain N/A.",vi:"Bite / Attack = AttackPower curve × base attack value; dữ liệu thiếu nguồn xác minh sẽ giữ N/A."}))+'</div></article></section>'+
    buildsSection+
    '<section class="section species-curve-section"><div class="section-head"><div><span class="eyebrow">LIFECYCLE CURVE</span><h2>'+E(U().primeCompare)+'</h2><p>'+E(U().derived)+'</p></div></div><div class="compare-wrap"><table><thead><tr><th>'+E(U().stage)+'</th><th>'+E(U().weight)+'</th><th>'+E(U().speed)+'</th><th>'+E(U().bite)+'</th><th>'+E(U().difference)+'</th></tr></thead><tbody>'+rows.map(r=>'<tr><th>'+E(U()[r.key])+'</th><td>'+KG(r.val.weight)+'</td><td>'+KMH(r.val.speed)+'</td><td>'+F(r.val.bite,1)+'</td><td>'+(r.key==="adult75"?"—":PCT(df(r.val.weight,base.weight))+" W · "+PCT(df(r.val.speed,base.speed))+" S · "+PCT(df(r.val.bite,base.bite))+" A")+'</td></tr>').join("")+'</tbody></table><div class="mobile-stat-stack">'+mobile+'</div></div></section>'+source(game.meta.sourceData||C.sources.species,"Raw game-data");
  }
function prime(){root.innerHTML=hero('<span>PRIME</span> & ELDER',E(tx(U().primeLead)),'<div class="hero-meta"><span class="meta-chip">5 / 10</span><span class="meta-chip">'+E(U().communityTested)+': small-species 4/10</span></div>')+'<section class="section"><div class="section-head"><div><span class="eyebrow">'+E(U().growthMilestones)+'</span><h2>75% → 87.5% → 100%</h2></div></div><div class="timeline"><div class="step"><strong>75%</strong><span>'+E(tx({th:"Adult baseline / เริ่มช่วง Prime",en:"Adult baseline / Prime activation",vi:"Mốc Adult / bắt đầu Prime"}))+'</span></div><div class="step"><strong>87.5%</strong><span>'+E(tx({th:"จุดสูงสุดของ Prime",en:"Prime peak milestone",vi:"Mốc Prime cao nhất"}))+'</span></div><div class="step"><strong>100%</strong><span>'+E(tx({th:"ปลายทาง Frail Elder / Prime Elder",en:"Frail Elder / Prime Elder endpoint",vi:"Mốc cuối Frail Elder / Prime Elder"}))+'</span></div><div class="step"><strong>4th Slot</strong><span>'+E(tx({th:"ใช้ตรวจ Prime ตาม current community guide",en:"In-game Prime check in the current community guide.",vi:"Cách kiểm tra Prime trong game theo guide cộng đồng."}))+'</span></div></div></section><section class="section"><div class="section-head"><div><span class="eyebrow">'+E(U().primeChecklist)+'</span><h2>'+E(U().primeConditions)+'</h2></div></div><div class="prime-conditions">'+C.primeConditions.map(c=>'<article class="prime-item '+(c.community?"community-tested":"")+'"><div class="prime-num">'+String(c.n).padStart(2,"0")+'</div><div><div class="badges"><span class="badge">'+E(conditionLabel(c.type))+'</span>'+(c.community?'<span class="badge community">'+E(U().communityTested)+'</span>':"")+'</div><h3>'+E(tx(c.title))+'</h3><p>'+E(tx(c.body))+'</p></div></article>').join("")+'</div></section><section class="section prose-grid"><article class="info-card"><h3>Prime / Frail</h3><p>'+E(tx({th:"โบนัส Prime ไม่เท่ากันทุก species — ใช้ Dinosaur Database ดู curve จริงรายตัว",en:"Prime bonuses differ by species — use the Dinosaur Database for each species' real curve.",vi:"Bonus Prime khác nhau theo loài — xem curve thật từng loài trong Dinosaur Database."}))+'</p></article><article class="info-card"><h3>Entomb</h3><p>'+E(tx({th:"แสดงเฉพาะ mechanics ที่ cross-check ได้; รายละเอียด community-tested จะติดป้ายแยก",en:"Only cross-checked mechanics are presented; community-tested details are labeled separately.",vi:"Chỉ hiển thị mechanics đã cross-check; chi tiết community-tested được gắn nhãn riêng."}))+'</p></article></section>'+source(C.sources.prime,"Prime community reference")+source(C.sources.thaiPrime,"Thai unlock reference")}
  function mutCard(x){
    const b=x.status==="test"?'<span class="badge test">'+E(U().test)+'</span>':x.status==="removed"?'<span class="badge removed">'+E(U().removed)+'</span>':'<span class="badge current">'+E(U().current)+'</span>';
    const BU=C.buildUi?.[state.lang]||C.buildUi?.en||{};
    const slotText=Array.isArray(x.equipSlots)?(x.equipSlots.length===4?(BU.allSlots||"All Slots"):x.equipSlots.map(n=>"Slot "+n).join(" / ")):(BU.needsVerification||"NEEDS VERIFICATION");
    const confidence=x.confidence==="community-tested"?U().communityTested:x.confidence==="community-reference"?(BU.communityReference||"COMMUNITY REFERENCE"):x.confidence==="needs-verification"?(BU.needsVerification||"NEEDS VERIFICATION"):x.confidence==="historical"?U().catRemoved:x.confidence==="test-reference"?U().catTest:(BU.communityReference||"COMMUNITY REFERENCE");
    const slotBadge=x.status==="current"?'<span class="badge">'+E(slotText)+'</span>':"";
    return '<article class="mutation-card"><div class="badges">'+b+'<span class="badge">'+E(categoryLabel(x.category))+'</span>'+(x.restriction?'<span class="badge">'+E(restrictionLabel(x.restriction))+'</span>':"")+slotBadge+'</div><h3>'+E(x.name)+'</h3><p>'+E(tx(x.effect))+(x.value?' <strong style="color:#d9c17e">'+E(x.value)+'</strong>':"")+'</p>'+(x.unlock?'<div class="unlock"><strong>'+E(U().howUnlock)+'</strong><br>'+E(tx(x.unlock))+'</div>':"")+'<div class="mutation-meta"><span class="badge">'+E(confidence)+'</span></div></article>';
  }
function mutations(){const cats=["all","Lifecycle","Slot Exclusive","Unlockable","Test / Horde","Removed"],list=C.mutations.filter(m=>{const hay=(m.name+" "+tx(m.effect)+" "+m.restriction+" "+m.slot+" "+tx(m.unlock||"")).toLowerCase();return(!state.query||hay.includes(state.query.toLowerCase()))&&(state.mutationCategory==="all"||m.category===state.mutationCategory)});root.innerHTML=hero('<span>MUTATION</span> DATABASE',E(tx(U().mutationLead)),'<div class="hero-meta"><span class="meta-chip"><strong>'+C.mutations.length+'</strong> '+E(U().records)+'</span></div>')+'<section class="section"><div class="toolbar"><div class="field"><label>'+E(U().search)+'</label><input id="mutationSearch" value="'+E(state.query)+'"></div><div class="field"><label>'+E(U().category)+'</label><select id="mutationFilter">'+cats.map(c=>'<option value="'+E(c)+'" '+(state.mutationCategory===c?"selected":"")+'>'+E(c==="all"?U().all:categoryLabel(c))+'</option>').join("")+'</select></div><div class="field"><label>'+E(U().status)+'</label><select disabled><option>'+E(U().contentScope)+'</option></select></div></div><div class="mutation-grid">'+(list.length?list.map(mutCard).join(""):'<div class="empty">'+E(U().noResults)+'</div>')+'</div></section>'+source(C.sources.mutations,"Mutation community reference")+source(C.sources.thaiMutations,"Thai unlock-method reference");document.getElementById("mutationSearch")?.addEventListener("input",e=>{state.query=e.target.value;mutations()});document.getElementById("mutationFilter")?.addEventListener("change",e=>{state.mutationCategory=e.target.value;mutations()})}
  function guideSection(k){const g=C.guides[k];root.innerHTML=hero('<span>'+E(tx(g.title))+'</span>',E(tx(g.lead)),'<div class="notice"><strong>GAME GUIDE</strong><br>'+E(U().guideNotice)+'</div>')+'<section class="section"><div class="prose-grid">'+g.cards.map(c=>'<article class="info-card"><h3>'+E(tx(c.h))+'</h3><p>'+E(tx(c.p))+'</p></article>').join("")+'</div></section>'+source(g.source,"Current guide reference")}
  function bindSpecies(){document.querySelectorAll(".species-card[data-species]").forEach(card=>{const go=()=>location.href="/dinosaurs/?species="+encodeURIComponent(card.dataset.species);card.addEventListener("click",go);card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();go()}})})}
  function render(){header();if(!root)return;if(page==="guide")hub();else if(page==="dinosaurs")dinosaurs();else if(page==="prime")prime();else if(page==="mutations")mutations();else if(C.guides[page])guideSection(page);else hub();bindSpecies()}
  document.querySelectorAll(".lang-btn").forEach(b=>b.addEventListener("click",()=>{state.lang=b.dataset.lang;localStorage.setItem("ki-rules-lang",state.lang);const r=document.getElementById("pageRoot");r?.classList.add("is-switching");setTimeout(()=>{render();r?.classList.remove("is-switching")},100)}));
  render();
})();