import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js";
import {OrbitControls} from "https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js";
import {GLTFLoader} from "https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/GLTFLoader.js";
import {KTX2Loader} from "https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/KTX2Loader.js";
import {MeshoptDecoder} from "https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/libs/meshopt_decoder.module.js";

const $=s=>document.querySelector(s), game=window.KI_GAME_DATA||{species:{}}, speciesName="Tyrannosaurus";
const species=game.species?.[speciesName]||null, state={growth:.75,path:"frail",animation:"Idle",playing:true,lang:"th"};
const ui={th:{lead:"ดูการเติบโตของ Tyrannosaurus แบบ 3D ด้วย morph จริง พร้อมค่าสถานะจาก lifecycle curve",loading:"กำลังโหลดโมเดล",ready:"พร้อมใช้งาน",fail:"โหลดโมเดลไม่สำเร็จ"},en:{lead:"Explore Tyrannosaurus growth with real 3D morphs and lifecycle gameplay curves.",loading:"LOADING MODEL",ready:"READY",fail:"MODEL LOAD FAILED"},vi:{lead:"Xem quá trình phát triển của Tyrannosaurus bằng morph 3D thật và dữ liệu lifecycle curve.",loading:"ĐANG TẢI MÔ HÌNH",ready:"SẴN SÀNG",fail:"KHÔNG TẢI ĐƯỢC MÔ HÌNH"}};

let renderer,scene,camera,controls,mixer,clock,model,clips={},currentAction=null,morphMeshes=[];
function bz(a,b,c,d,t){const q=1-t;return q*q*q*a+3*q*q*t*b+3*q*t*t*c+t*t*t*d}
function wb(p){return p&&(p.w===1||p.w===3)} function wa(p){return p&&(p.w===2||p.w===3)}
function rw(a,b,t){const span=b.t-a.t,target=(t-a.t)/span,leave=a.lt??0,arrive=b.at??0;let ang=Math.atan(leave);const lw=wa(a)?(a.lw??0):Math.hypot(span,leave*span)/3;const p1t=Math.cos(ang)*lw+a.t,p1v=Math.sin(ang)*lw+a.v;ang=Math.atan(arrive);const aw=wb(b)?(b.aw??0):Math.hypot(span,arrive*span)/3;const p2t=-Math.cos(ang)*aw+b.t,p2v=-Math.sin(ang)*aw+b.v,c1=(p1t-a.t)/span,c2=(p2t-a.t)/span;let lo=0,hi=1;for(let i=0;i<50;i++){const m=(lo+hi)/2;bz(0,c1,c2,1,m)<target?lo=m:hi=m}return bz(a.v,p1v,p2v,b.v,(lo+hi)/2)}
function rc(points,t){if(!Array.isArray(points)||!points.length)return null;const first=points[0],last=points[points.length-1];if(t<=first.t)return first.v;if(t>=last.t)return last.v;for(let i=0;i<points.length-1;i++){const a=points[i],b=points[i+1];if(t<a.t||t>b.t)continue;const span=b.t-a.t;if(span<=0)return a.v;const p=(t-a.t)/span;if(!a.c)return a.v+(b.v-a.v)*p;if(a.w||b.w)return rw(a,b,t);const m0=(a.lt??0)*span,m1=(b.at??0)*span,p2=p*p,p3=p2*p;return(2*p3-3*p2+1)*a.v+(p3-2*p2+p)*m0+(-2*p3+3*p2)*b.v+(p3-p2)*m1}return null}
function curve(k){const c=species?.curves?.[k];return c?rc(state.path==="prime"?c.prime:c.frail,state.growth):null}
function updateStats(){const w=curve("Weight"),s=curve("SprintSpeed"),a=curve("AttackPower"),b=a!=null&&species?.damageBite!=null?a*species.damageBite:null;$("#weightStat").textContent=w==null?"N/A":w.toLocaleString("en-US",{maximumFractionDigits:1})+" kg";$("#speedStat").textContent=s==null?"N/A":(s*.036).toFixed(1)+" km/h";$("#attackStat").textContent=a==null?"N/A":a.toFixed(3);$("#biteStat").textContent=b==null?"N/A":b.toFixed(1)}
function stageFor(g){const stages=["HATCHLING","JUVENILE","SUBADULT","ADULT","ELDER"],x=g*4,i=Math.min(4,Math.floor(x));return stages[i]}
function applyGrowth(){const g=THREE.MathUtils.clamp(state.growth,0,1),x=g*4,left=Math.min(3,Math.floor(x)),mix=x-left;const weights={Hatchling:0,Juvenile:0,SubAdult:0,Elder:0};if(left===0){weights.Hatchling=1-mix;weights.Juvenile=mix}else if(left===1){weights.Juvenile=1-mix;weights.SubAdult=mix}else if(left===2){weights.SubAdult=1-mix}else if(left===3){weights.Elder=mix}else if(g===1){weights.Elder=1}for(const mesh of morphMeshes){const dict=mesh.morphTargetDictionary||{};for(const [name,val] of Object.entries(weights)){const idx=dict[name];if(idx!==undefined)mesh.morphTargetInfluences[idx]=val}}const pct=(g*100).toFixed(g*100%1?1:0);$("#growthOutput").textContent=pct+"%";$("#stageChip").textContent=pct+"% · "+stageFor(g);updateStats();syncUrl()}
function syncUrl(){const u=new URL(location.href);u.searchParams.set("species",speciesName);u.searchParams.set("growth",(state.growth*100).toFixed(1).replace(".0",""));u.searchParams.set("path",state.path);u.searchParams.set("animation",state.animation);history.replaceState(null,"",u)}
function setAnimation(name){state.animation=name;$("#animationSelect").value=name;if(!mixer||!clips[name])return;if(currentAction)currentAction.fadeOut(.2);currentAction=mixer.clipAction(clips[name]);currentAction.reset().fadeIn(.2).play();currentAction.paused=!state.playing;syncUrl()}
function resetCamera(){camera.position.set(7,3.2,9);controls.target.set(0,1.8,0);controls.update()}
function setLang(lang){state.lang=lang;localStorage.setItem("ki-rules-lang",lang);document.documentElement.lang=lang;document.querySelectorAll("[data-lang]").forEach(b=>b.classList.toggle("active",b.dataset.lang===lang));$("#viewerLead").textContent=ui[lang].lead}
function initScene(){if(!window.WebGLRenderingContext){$("#fallback").hidden=false;return}const canvas=$("#viewerCanvas");renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x0a0d0a,.025);camera=new THREE.PerspectiveCamera(35,1,.1,100);controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.minDistance=3;controls.maxDistance=20;controls.maxPolarAngle=Math.PI*.54;resetCamera();scene.add(new THREE.HemisphereLight(0xb9c5af,0x20170f,1.6));const key=new THREE.DirectionalLight(0xffddb0,3.4);key.position.set(6,8,5);scene.add(key);const rim=new THREE.DirectionalLight(0x89a889,2.1);rim.position.set(-5,4,-7);scene.add(rim);const floor=new THREE.Mesh(new THREE.CircleGeometry(7,64),new THREE.MeshStandardMaterial({color:0x10140f,roughness:1,metalness:0}));floor.rotation.x=-Math.PI/2;floor.position.y=-.03;scene.add(floor);clock=new THREE.Clock();const ro=new ResizeObserver(resize);ro.observe($("#canvasWrap"));loadModel();animate()}
function resize(){if(!renderer)return;const el=$("#canvasWrap"),w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
function loadModel(){const loader=new GLTFLoader();loader.setMeshoptDecoder(MeshoptDecoder);const ktx2=new KTX2Loader().setTranscoderPath("https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/libs/basis/");ktx2.detectSupport(renderer);loader.setKTX2Loader(ktx2);$("#loadStatus").textContent=ui[state.lang].loading;loader.load("/assets/viewer/Tyrannosaurus/Tyrannosaurus.glb",gltf=>{model=gltf.scene;const box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());model.position.sub(center);model.position.y+=size.y*.48;const scale=5.5/Math.max(size.x,size.y,size.z);model.scale.setScalar(scale);model.traverse(o=>{if(o.isMesh){o.castShadow=false;o.receiveShadow=false;if(o.morphTargetDictionary&&o.morphTargetInfluences)morphMeshes.push(o);if(o.material){o.material.needsUpdate=true}}});scene.add(model);mixer=new THREE.AnimationMixer(model);for(const c of gltf.animations)clips[c.name]=c;setAnimation(clips.Idle?"Idle":Object.keys(clips)[0]);applyGrowth();$("#loadStatus").textContent=ui[state.lang].ready},undefined,e=>{console.error("Viewer model load failed",e);$("#loadStatus").textContent=ui[state.lang].fail;$("#fallback").hidden=false})}
function animate(){requestAnimationFrame(animate);const dt=clock?.getDelta()||0;if(mixer&&state.playing)mixer.update(dt);controls?.update();renderer?.render(scene,camera)}
function bind(){const q=new URLSearchParams(location.search),g=Number(q.get("growth"));if(Number.isFinite(g))state.growth=THREE.MathUtils.clamp(g/100,0,1);if(["frail","prime"].includes(q.get("path")))state.path=q.get("path");if(q.get("animation"))state.animation=q.get("animation");state.lang=localStorage.getItem("ki-rules-lang")||"th";$("#growthSlider").value=state.growth*100;document.querySelectorAll("[data-path]").forEach(b=>b.classList.toggle("active",b.dataset.path===state.path));setLang(["th","en","vi"].includes(state.lang)?state.lang:"th");$("#growthSlider").addEventListener("input",e=>{state.growth=Number(e.target.value)/100;applyGrowth()});document.querySelectorAll("[data-path]").forEach(b=>b.addEventListener("click",()=>{state.path=b.dataset.path;document.querySelectorAll("[data-path]").forEach(x=>x.classList.toggle("active",x===b));updateStats();syncUrl()}));$("#animationSelect").addEventListener("change",e=>setAnimation(e.target.value));$("#playPause").addEventListener("click",()=>{state.playing=!state.playing;$("#playPause").textContent=state.playing?"Pause":"Play";if(currentAction)currentAction.paused=!state.playing});$("#resetCamera").addEventListener("click",resetCamera);document.querySelectorAll("[data-lang]").forEach(b=>b.addEventListener("click",()=>setLang(b.dataset.lang)));$("#retryBtn").addEventListener("click",()=>location.reload());updateStats()}
bind();initScene();